name: yt-storage-decrypt

networks:
  intranet:
    driver: bridge

services:
  yt-storage-decrypt:
    image: jadit19/yt-storage:latest
    container_name: yt-storage-decrypt
    restart: 'no'
    networks:
      - intranet
    volumes:
      - ../files:/files
    environment:
      INPUT_FILE: 'output.mp4'
      MODE: '1'
