name: yt-storage-encrypt

networks:
  intranet:
    driver: bridge

services:
  yt-storage-encrypt:
    image: jadit19/yt-storage:latest
    container_name: yt-storage-encrypt
    restart: 'no'
    networks:
      - intranet
    volumes:
      - ../files:/files
    environment:
      MODE: '0'
      INPUT_PATH: '/files/important-video.mp4'
      OUTPUT_DIR: '/files'
      OUTPUT_FILE: 'output.mp4'
      WIDTH: '1920'
      HEIGHT: '1080'
      FPS: '30'
